### ISSUE TITLE
Separate the store into "background" symbols and symbols from the current project

### ISSUE THREAD

**Issue by davidanthoff** [ZacLN/StaticLint.jl#10]
This point might be nonsense and based on my misunderstanding of the code here ;) But my understanding is that ``store`` right now holds all the symbols from packages that the code that is being linted depends on, and that the linter then *also* adds symbols from the project that is being linted to ``store``, correct?

Could we split this, so that we have a ``store`` that is only the symbols from things that are loaded by the linted project, and a separate ``project_store`` that has all the symbols from the project that is being linted? It would mean that whenever one is looking up something, one would have to look in both stores... But the upside would be that we could super easily discard the environment store and replace it with a new one if the user switches environment...

**Comment by ZacLN** [comment]
That's how it currently works! 

It builds a symbol table by traversing the code and marks using/import statements. These are then revisited, and if specific symbols are imported (i.e. import m:a,b) they are added to the symbol table. Base/Core and any `using`ed modules are added to a used_modules list which is then checked separately when resolving a `Reference`.
